version: "3.9"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend/public:/usr/share/nginx/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: tagamiroot
      MYSQL_DATABASE: tagami_db
      MYSQL_USER: sql_user
      MYSQL_PASSWORD: sql_pass
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=tagamiroot
    networks:
      - app-network
    ports:
      - "3001:80"

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./backend/app:/app
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
